### ISSUE TITLE
Error while running analyze (solc missing)

### ISSUE THREAD

**Issue by xale76** [ApeWorX/py-solc-x#150]
### Environment information

* `py-solc-x` Version: x.x.x
* `solc` Version: x.x.x
* Python Version: x.x.x
* OS: osx/linux/win

### What was wrong?

Please include information like:

* what command you ran
* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)
* full output of the error you received

### How can it be fixed?

Fill this in if you know how the bug could be fixed.

**Comment by xale76** [comment]
Hello I cannot run my mythx analyze
I got

Usage: mythx analyze [OPTIONS] [TARGET]...

Error: Error installing solc version v0.9.0: 404 error when attempting to download from
https://github.com/ethereum/solidity/releases/download/v0.8.4/solidity-windows.zip - are you sure this version of solidity is available?

py-solc-x: ???
solc: I have truffle and I use ^0.8.4
Python: 3.10.4
OS: windows 10

**Comment by antazoey** [comment]
If you using truffle solc, you likely are not using this package. This is a python package! We also use the tar ball links so I don' t think your issue is coming from us, or else I need more info.

The link this package would use is https://github.com/ethereum/solidity/releases/download/v0.8.5/solidity_0.8.5.tar.gz
